name: quiz_star
description: We've got all the quizzes you love to binge! Come on in and hunker down for the long haul.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  video_player: ^0.10.11+2
  social_share: ^2.0.5
  image_picker: ^0.6.7+4
  http: ^0.12.2
  screenshot: ^0.2.0
  url_launcher: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.0"
flutter_icons:
  android: true 
  ios: true
  image_path: "asset/images/logo.png"
  adaptive_icon_foreground: "asset/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - asset/images/cupGold.png
    - asset/images/cupSilver.png
    - asset/images/cupBronse.png
    - asset/images/noCup.png
    - asset/videos/congratulation.mp3
    - asset/videos/start_sound_button.mp3
    - asset/videos/Answer_click.mp3


  fonts:   
    - family: MyIcon
      fonts:
        - asset: asset/fonts/MyIcon.ttf                        
    - family: Raleway
      fonts:
        - asset: asset/fonts/Raleway-Black.ttf                    
        - asset: asset/fonts/Raleway-Bold.ttf                    
        - asset: asset/fonts/Raleway-Regular.ttf            
    - family: RobotoCondensed
      fonts:
        - asset: asset/fonts/RobotoCondensed-Light.ttf                    
        - asset: asset/fonts/RobotoCondensed-Bold.ttf
          weight: 700               
        - asset: asset/fonts/RobotoCondensed-Regular.ttf    
        - asset: asset/fonts/RobotoCondensed-Italic.ttf    
          style: italic