/// Flutter icons Icon4
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Icon4
///      fonts:
///       - asset: fonts/Icon4.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Icon4 {
  Icon4._();

  static const _kFontFam = 'Icon4';
  static const _kFontPkg = null;

  static const IconData expeditedssl = IconData(0xf23e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
