/// Flutter icons Icon2
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Icon2
///      fonts:
///       - asset: fonts/Icon2.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class Icon2 {
  Icon2._();

  static const _kFontFam = 'Icon2';
  static const _kFontPkg = null;

  static const IconData casino =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
