/// Flutter icons Icon3
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Icon3
///      fonts:
///       - asset: fonts/Icon3.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Icon3 {
  Icon3._();

  static const _kFontFam = 'Icon3';
  static const _kFontPkg = null;

  static const IconData beaker = IconData(0xf0c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
